// Mirrors client/src/services/realtime/events.js.
//
// RELAY: ephemeral events forwarded as-is to the other person in the couple.
// Things that must be persisted or paid for (chat messages, gifts, letters,
// memories, plans, check-ins) are NOT relayed from clients — the REST
// handlers emit them after saving, so they can't be spoofed.
export const RELAY = new Set([
  'presence:update',
  'chat:typing',
  'chat:read',
  'chat:reaction',
  'interaction',
  'interaction:hug',
  'interaction:kiss',
  'interaction:wave',
  'interaction:love',
  'interaction:highfive',
  'interaction:pat',
  'activity:invite',
  'activity:accepted',
  'activity:declined',
  'activity:leave',
  'movie:load',
  'movie:play',
  'movie:pause',
  'movie:seek',
  'movie:state',
  'movie:cue',
  // cinema: where each of us is in the theatre, and the film streamed by the host
  'theatre:state',
  'stream:offer',
  'stream:answer',
  'stream:ice',
  'stream:request',
  'stream:stop',
  'movie:reaction',
  'call:reaction',
  'music:play',
  'music:pause',
  'music:track',
  'dance:start',
  'dance:stop',
  'room:update',
  'avatar:update',
  'memory:reaction',
  'pet:update',
  'rtc:call',
  'rtc:accept',
  'rtc:end',
  'rtc:offer',
  'rtc:answer',
  'rtc:ice',
]);
